[package]
name = "remove_key"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-contract="1.4.3"
casper-types="1.4.6"

[[bin]]
name = "remove_key"
path = "src/main.rs"
bench = false
doctest = false
test = false